//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// --------------------------------------------------------------------------------------------------
// <auto-generatedInfo>
// 	This code was generated by ResW File Code Generator (http://reswcodegen.codeplex.com)
// 	ResW File Code Generator was written by Christian Resma Helle
// 	and is under GNU General Public License version 2 (GPLv2)
// 
// 	This code contains a helper class exposing property representations
// 	of the string resources defined in the specified .ResW file
// 
// 	Generated: 08/22/2015 18:15:32
// </auto-generatedInfo>
// --------------------------------------------------------------------------------------------------
namespace AdaptiveTileExtensions.Testing
{
    using Windows.ApplicationModel.Resources;
    
    
    internal partial class Resources
    {
        
        private static ResourceLoader resourceLoader;
        
        static Resources()
        {
            string executingAssemblyName;
            executingAssemblyName = Windows.UI.Xaml.Application.Current.GetType().AssemblyQualifiedName;
            string[] executingAssemblySplit;
            executingAssemblySplit = executingAssemblyName.Split(',');
            executingAssemblyName = executingAssemblySplit[1];
            string currentAssemblyName;
            currentAssemblyName = typeof(Resources).AssemblyQualifiedName;
            string[] currentAssemblySplit;
            currentAssemblySplit = currentAssemblyName.Split(',');
            currentAssemblyName = currentAssemblySplit[1];
            if (executingAssemblyName.Equals(currentAssemblyName))
            {
                resourceLoader = ResourceLoader.GetForCurrentView("Resources");
            }
            else
            {
                resourceLoader = ResourceLoader.GetForCurrentView(currentAssemblyName + "/Resources");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "<?xml version="1.0"?>
        ///<tile version="3">
        ///<visual>
        ///<binding template="TileWide" branding="NameAndLogo">
        ///<image src="http://fc02.deviantart.net/fs71/i/2013/359/a/4/deadpool_logo_1_fill_by_mr_droy-d5q6y5u.png" placement="Background" />
        ///<group>
        ///<subgroup>
        ///<text hint-style="header">You have mail</text>
        ///<text hint-style="caption">Someone likes you!</text>
        ///</subgroup>
        ///</group>
        ///</binding>
        ///<binding template="TileMedium" branding="None">
        ///<group>
        ///<subgroup hint-weight="20">
        ///<image src="http://fc02.deviantart.net/fs71/i/2013/359/a/4/deadpool_logo_1_fill_by_mr_droy-d5q6y5u.png" placement="Inline" />
        ///</subgroup>
        ///<subgroup>
        ///<text hint-style="body" hint-wrap="true">You have mail</text>
        ///<text hint-style="captionSubtle" hint-align="Center" hint-wrap="true">Someone likes you!</text>
        ///</subgroup>
        ///</group>
        ///</binding>
        ///</visual>
        ///</tile>"
        /// </summary>
        public static string ExpectedTransform
        {
            get
            {
                return resourceLoader.GetString("ExpectedTransform");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "<?xml version="1.0"?><Tile xmlns:a="http://www.w3.org/2001/XMLSchema" xmlns:i="http://www.w3.org/2001/XMLSchema-instance" xmlns="https://github.com/ScottIsAFool/AdaptiveTileExtensions"><Bindings><TileBinding><Branding i:type="Branding">NameAndLogo</Branding><Items><Item i:type="TileImage"><Placement>Background</Placement><Source>http://fc02.deviantart.net/fs71/i/2013/359/a/4/deadpool_logo_1_fill_by_mr_droy-d5q6y5u.png</Source></Item><Item i:type="Group"><Children><Item i:type="SubGroup"><Children><Item i:type="Text"><Content>You have mail</Content><Style i:type="TextStyle">Header</Style></Item><Item i:type="Text"><Content>Someone likes you!</Content><Style i:type="TextStyle">Caption</Style></Item></Children></Item></Children></Item></Items><TemplateType>TileWide</TemplateType></TileBinding><TileBinding><Branding i:type="Branding">None</Branding><Items><Item i:type="Group"><Children><Item i:type="SubGroup"><Children><Item i:type="TileImage"><Placement>Inline</Placement><Source>http://fc02.deviantart.net/fs71/i/2013/359/a/4/deadpool_logo_1_fill_by_mr_droy-d5q6y5u.png</Source></Item></Children><Width i:type="a:int">20</Width></Item><Item i:type="SubGroup"><Children><Item i:type="Text"><Content>You have mail</Content><Style i:type="TextStyle">Body</Style><WrapText i:type="a:boolean">true</WrapText></Item><Item i:type="Text"><Alignment i:type="Alignment">Center</Alignment><Content>Someone likes you!</Content><IsSubtleStyle i:type="a:boolean">true</IsSubtleStyle><Style i:type="TextStyle">Caption</Style><WrapText i:type="a:boolean">true</WrapText></Item></Children></Item></Children></Item></Items><TemplateType>TileMedium</TemplateType></TileBinding></Bindings><Version>3</Version></Tile>"
        /// </summary>
        public static string ExpectedXml
        {
            get
            {
                return resourceLoader.GetString("ExpectedXml");
            }
        }
    }
}
